export const DEMO_SCENARIOS = [
  {
    name: 'Highway Cruise',
    description: 'Three-lane highway, clear ahead',
    duration: 4000,
    data: {
      timestamp: 0, frame: 0,
      road: { type: 'straight', lanes: 3, width: 18, length: 200, separator: 'dashed_white' },
      junction: null,
      detections: [
        { id: 1, class: 'car',   distance_m: 35, position: 'front_right', orientation: 'same', junction_road: false },
        { id: 2, class: 'truck', distance_m: 50, position: 'front',       orientation: 'same', junction_road: false },
        { id: 3, class: 'car',   distance_m: 28, position: 'left',        orientation: 'opposite', junction_road: false },
      ],
      decisions: { brake: 'none', lane: 'keep', speed: 'maintain', risk: 'low' },
      lane_info: { num_lanes: 3, current_lane: 2, is_main_road: true, lane_center_offset_px: -8, lane_confidence: 0.91 },
      alert_triggers: { vehicle_ahead: false, stop_sign: false, red_traffic_light: false },
    },
  },
  {
    name: 'Car Cutting In',
    description: 'Vehicle merging from right — increase following distance',
    duration: 4000,
    data: {
      timestamp: 4, frame: 8,
      road: { type: 'straight', lanes: 3, width: 18, length: 200, separator: 'dashed_white' },
      junction: null,
      detections: [
        { id: 1, class: 'car', distance_m: 12, position: 'front',       orientation: 'same', junction_road: false },
        { id: 2, class: 'car', distance_m: 18, position: 'front_right', orientation: 'same', junction_road: false },
        { id: 3, class: 'car', distance_m: 40, position: 'front_left',  orientation: 'same', junction_road: false },
      ],
      decisions: { brake: 'light', lane: 'keep', speed: 'decrease', risk: 'medium' },
      lane_info: { num_lanes: 3, current_lane: 2, is_main_road: true, lane_center_offset_px: 14, lane_confidence: 0.87 },
      alert_triggers: { vehicle_ahead: true, stop_sign: false, red_traffic_light: false },
    },
  },
  {
    name: 'City Street',
    description: 'Two-lane city road — pedestrian crossing',
    duration: 4000,
    data: {
      timestamp: 8, frame: 16,
      road: { type: 'straight', lanes: 2, width: 12, length: 200, separator: 'solid_yellow' },
      junction: null,
      detections: [
        { id: 1, class: 'person', distance_m:  8, position: 'front',      orientation: 'same', junction_road: false },
        { id: 2, class: 'car',    distance_m: 20, position: 'front_left', orientation: 'opposite', junction_road: false },
      ],
      decisions: { brake: 'strong', lane: 'keep', speed: 'decrease', risk: 'high' },
      lane_info: { num_lanes: 2, current_lane: 1, is_main_road: false, lane_center_offset_px: 22, lane_confidence: 0.74 },
      alert_triggers: { vehicle_ahead: true, stop_sign: false, red_traffic_light: false },
    },
  },
  {
    name: 'Red Traffic Light',
    description: 'Intersection — stop for red light',
    duration: 4500,
    data: {
      timestamp: 12, frame: 24,
      road: { type: 'straight', lanes: 2, width: 12, length: 200, separator: 'solid_yellow' },
      junction: { type: 'cross', distance_m: 22, road_in: { direction: 'both', lanes: 2, width: 10, length: 55 } },
      detections: [
        { id: 1, class: 'traffic_light', distance_m: 18, position: 'front', orientation: 'same', junction_road: false },
        { id: 2, class: 'car',           distance_m: 35, position: 'right', orientation: 'same', junction_road: true  },
      ],
      decisions: { brake: 'strong', lane: 'keep', speed: 'decrease', risk: 'high' },
      lane_info: { num_lanes: 2, current_lane: 1, is_main_road: false, lane_center_offset_px: 5, lane_confidence: 0.82 },
      alert_triggers: { vehicle_ahead: false, stop_sign: false, red_traffic_light: true },
    },
  },
  {
    name: 'T-Junction Approach',
    description: 'Car entering from the left side road',
    duration: 5000,
    data: {
      timestamp: 17, frame: 34,
      road: { type: 'straight', lanes: 2, width: 12, length: 200, separator: 'double_yellow' },
      junction: { type: 'T', distance_m: 28, road_in: { direction: 'left', lanes: 2, width: 11, length: 60 } },
      detections: [
        { id: 1, class: 'car', distance_m: 28, position: 'left',  orientation: 'same', junction_road: true  },
        { id: 2, class: 'car', distance_m: 22, position: 'front', orientation: 'same', junction_road: false },
      ],
      decisions: { brake: 'light', lane: 'keep', speed: 'decrease', risk: 'medium' },
      lane_info: { num_lanes: 2, current_lane: 1, is_main_road: false, lane_center_offset_px: -3, lane_confidence: 0.78 },
      alert_triggers: { vehicle_ahead: true, stop_sign: false, red_traffic_light: false },
    },
  },
  {
    name: 'Crossroads',
    description: 'Vehicles crossing from both sides',
    duration: 5000,
    data: {
      timestamp: 22, frame: 44,
      road: { type: 'straight', lanes: 2, width: 12, length: 200, separator: 'solid_white' },
      junction: { type: 'cross', distance_m: 28, road_in: { direction: 'both', lanes: 2, width: 11, length: 60 } },
      detections: [
        { id: 1, class: 'car', distance_m: 28, position: 'right', orientation: 'same', junction_road: true  },
        { id: 2, class: 'car', distance_m: 28, position: 'left',  orientation: 'same', junction_road: true  },
        { id: 3, class: 'car', distance_m: 10, position: 'front', orientation: 'same', junction_road: false },
      ],
      decisions: { brake: 'strong', lane: 'keep', speed: 'decrease', risk: 'high' },
      lane_info: { num_lanes: 2, current_lane: 1, is_main_road: false, lane_center_offset_px: 0, lane_confidence: 0.68 },
      alert_triggers: { vehicle_ahead: true, stop_sign: false, red_traffic_light: false },
    },
  },
  {
    name: 'Stop Sign',
    description: 'Stop sign detected ahead — full stop required',
    duration: 4000,
    data: {
      timestamp: 27, frame: 54,
      road: { type: 'straight', lanes: 2, width: 12, length: 200, separator: 'solid_yellow' },
      junction: { type: 'T', distance_m: 20, road_in: { direction: 'right', lanes: 1, width: 8, length: 50 } },
      detections: [
        { id: 1, class: 'stop_sign', distance_m: 18, position: 'front', orientation: 'same', junction_road: false },
      ],
      decisions: { brake: 'strong', lane: 'keep', speed: 'decrease', risk: 'high' },
      lane_info: { num_lanes: 2, current_lane: 1, is_main_road: false, lane_center_offset_px: -11, lane_confidence: 0.85 },
      alert_triggers: { vehicle_ahead: false, stop_sign: true, red_traffic_light: false },
    },
  },
  {
    name: 'Lane Change Left',
    description: 'Slow truck ahead — safe to overtake',
    duration: 4000,
    data: {
      timestamp: 31, frame: 62,
      road: { type: 'straight', lanes: 3, width: 18, length: 200, separator: 'dashed_white' },
      junction: null,
      detections: [
        { id: 1, class: 'truck', distance_m: 15, position: 'front',      orientation: 'same', junction_road: false },
        { id: 2, class: 'car',   distance_m: 45, position: 'front_left', orientation: 'same', junction_road: false },
      ],
      decisions: { brake: 'none', lane: 'change_left', speed: 'maintain', risk: 'low' },
      lane_info: { num_lanes: 3, current_lane: 2, is_main_road: true, lane_center_offset_px: 4, lane_confidence: 0.93 },
      alert_triggers: { vehicle_ahead: false, stop_sign: false, red_traffic_light: false },
    },
  },
  {
    name: 'Low Confidence / Fog',
    description: 'Poor lane visibility — uncertain lane count',
    duration: 3500,
    data: {
      timestamp: 35, frame: 70,
      road: { type: 'straight', lanes: 2, width: 12, length: 200, separator: 'dashed_white' },
      junction: null,
      detections: [
        { id: 1, class: 'car', distance_m: 25, position: 'front', orientation: 'same', junction_road: false },
      ],
      decisions: { brake: 'none', lane: 'keep', speed: 'maintain', risk: 'low' },
      lane_info: { num_lanes: 2, current_lane: 1, is_main_road: false, lane_center_offset_px: 31, lane_confidence: 0.18 },
      alert_triggers: { vehicle_ahead: false, stop_sign: false, red_traffic_light: false },
      env_conditions: ['fog'],
    },
  },
  {
    name: 'Dense Traffic',
    description: 'Five detections — busy urban road',
    duration: 4500,
    data: {
      timestamp: 39, frame: 78,
      road: { type: 'straight', lanes: 3, width: 18, length: 200, separator: 'dashed_white' },
      junction: null,
      detections: [
        { id: 1, class: 'car',           distance_m:  9, position: 'front',       orientation: 'same',     junction_road: false },
        { id: 2, class: 'car',           distance_m: 16, position: 'front_left',  orientation: 'same',     junction_road: false },
        { id: 3, class: 'truck',         distance_m: 30, position: 'front_right', orientation: 'same',     junction_road: false },
        { id: 4, class: 'car',           distance_m: 14, position: 'left',        orientation: 'opposite', junction_road: false },
        { id: 5, class: 'traffic_light', distance_m: 40, position: 'front',       orientation: 'same',     junction_road: false },
      ],
      decisions: { brake: 'light', lane: 'keep', speed: 'decrease', risk: 'medium' },
      lane_info: { num_lanes: 3, current_lane: 2, is_main_road: true, lane_center_offset_px: -18, lane_confidence: 0.79 },
      alert_triggers: { vehicle_ahead: true, stop_sign: false, red_traffic_light: false },
    },
  },
];